### ISSUE TITLE
Database Push Bug

### ISSUE THREAD

**Issue by jvherck** [ZexZee/DiscordDiceroller#1]
Hi, your bot is really great! I'm using it as base for my own bot. However, I'm still rewriting it (to cogs and stuff) and now whenever I restart the bot, it doesn't push the most updated version of the users database, it pushes them all into the database.
Example:
I have 1000 coins in my balance, and that's saved in the database. The next day, I restart the bot again to work on it again. I do `?daily` and get 500 coins. So when I do `?bal` it shows me i have 1500 coins. I do the forcesave command and it doesnt just push 1500 into the database, it also pushes the previous line (1000) in the database. 

How could I solve this?

> Empty database
> ![image](https://user-images.githubusercontent.com/75937214/108494875-59b46980-72a8-11eb-90c8-ab1a273d315d.png)

> I have been registered
> ![image](https://user-images.githubusercontent.com/75937214/108494984-7ea8dc80-72a8-11eb-8cae-e4fd4efb27e2.png)

> I did daily
> ![image](https://user-images.githubusercontent.com/75937214/108495047-954f3380-72a8-11eb-86fd-9afad583e7cd.png)

> I forcesaved it
> ![image](https://user-images.githubusercontent.com/75937214/108495122-ac8e2100-72a8-11eb-85b9-1a0977c9846b.png)

> I stopped the bot (when I want to change the code of course I have to stop and re-run)
> ![image](https://user-images.githubusercontent.com/75937214/108495202-c92a5900-72a8-11eb-8ef8-e401e0546aa4.png)

> I re-run the code and the database is still the same
> ![image](https://user-images.githubusercontent.com/75937214/108495318-ef4ff900-72a8-11eb-9c04-9c965c2e5479.png)
> ![image](https://user-images.githubusercontent.com/75937214/108495362-fd9e1500-72a8-11eb-8f98-3355dabd8ca9.png)

> I do the raffle command to give me some more money for this test and see I did get it to my balance
> ![image](https://user-images.githubusercontent.com/75937214/108495495-258d7880-72a9-11eb-8412-231d0b2a2eaf.png)

> I forcesave the database and get this. Both the balances of before and after the forcesave get pushed
> ![image](https://user-images.githubusercontent.com/75937214/108495644-58377100-72a9-11eb-8905-66627c9632ae.png)

> Again I get more money and forcesave it
> ![image](https://user-images.githubusercontent.com/75937214/108495784-80bf6b00-72a9-11eb-860f-a423d81e1849.png)

> Then this happens: it does update the latest one...
> ![image](https://user-images.githubusercontent.com/75937214/108495853-959bfe80-72a9-11eb-8cfa-6c6540cc23e2.png)

> Again I get more money and see it's in my bal
> ![image](https://user-images.githubusercontent.com/75937214/108495945-b6fcea80-72a9-11eb-8fb5-8fe58a8018e8.png)

> I forcesave it and it updates the latest one again
> ![image](https://user-images.githubusercontent.com/75937214/108496011-d0059b80-72a9-11eb-8ece-c69ba7136e31.png)

> Now I removed the old balance and again got more money
> ![image](https://user-images.githubusercontent.com/75937214/108496109-eca1d380-72a9-11eb-98ec-99a5d7edae25.png)

> I forcesave it and it just pushes a new line out of nothing into the database
> ![image](https://user-images.githubusercontent.com/75937214/108496227-11964680-72aa-11eb-8b1d-03b486d86c49.png)

As you can see in the previous image, I raffled 5000, so where does that 1500 come from suddenly? It seems like it always wants the users 2 times in the database. When doing bal if you're 2 times in the database, it picks the top one, so the most updated one...

**Comment by Z3tty** [comment]
IIRC, the bug is caused by an empty DB on startup, which causes the bot to register you (which writes you to the file) and also, due to your user object changing due to chat activity, queues a db.push() task. This probably just ends up writing the internal state again, somehow. I'm sure I could discover exactly how in a day or two, but the bot is an old project, and I don't really have the time.

With that said, does removing the "old" entry solve the double-write, or does it keep a "ghost record" of the #0 user at all times?
If the prior, then I'd recommend just keeping your own entry in it as a "patch" to avoid the bug. If the latter, then I'd recommend combing through the db.push() and db.register() methods. I apologize for the somewhat disgustingly undocumented code.

**Comment by jvherck** [comment]
When I remove the unnecessary user, it just appears back upon chatting. And also, when #0 is in there, and I restart the bot, it copies that along, so meaning there's 4 users lol. I guess I can try to make a new db system. 
It's really cool how you've made this though! You’re a legend, keep going!

**Comment by jvherck** [comment]
Okay so I solved the problem.... My dumbass did `DATABASE.pull()` right after the imports *and* in the `on_ready` event, so that's why it always kept pushing it twice. I removed one of them and now it works fine. I restarted it multiple times and it only updates each user 1 time. Thanks for being so awesome and making such an awesome template!

**Comment by Z3tty** [comment]
Ah, yeah, that'll do it.
